spring.application.name=ordinyan-coursework-app
server.port=${APP_PORT:8081}
spring.datasource.url=${APP_DB_URL:jdbc:postgresql://localhost:5433/ordinyan_coursework}
spring.datasource.username=${APP_DB_USERNAME:postgres}
spring.datasource.password=${APP_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Moscow
spring.thymeleaf.cache=false
server.error.include-message=always
