services:
  postgres:
    image: postgres:16-alpine
    container_name: ordinyan-coursework-postgres
    environment:
      POSTGRES_DB: ordinyan_coursework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ordinyan-coursework-postgres-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ordinyan_coursework"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  ordinyan-coursework-postgres-data:
